name: (M) Behat Tests
on:
  workflow_call:
    secrets:
      slack_token:
        description: "API token for slack"
      site:
        description: "Site to run tests on"
      database:
        description: "Database to pull in, normally blank"
      prnum:
        description: "Pull request number"
      gh_token:
        description: "A github token"
      LANDO_ENV:
        description: "Lando environment variables"
      SLACK_WEBHOOK:
        description: "Slack webhook to communicate with api"
      REPO:
        description: "Get current repo for gh cli command to comment on PR"
permissions:
  contents: write
  actions: read
  pull-requests: write
jobs:
  behat:
    name: Run behat tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - id: Lando
        uses: necyberteam/amp_lando_start@v2.2
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run behat test
        run: |
          pwd
          lando ssh -c 'pwd'
          lando blt amp:behat $SITE
        env:
          SITE: ${{ secrets.site }}

      - name: Slack Notification Fail
        uses: MeilCli/slack-upload-file@v4.0.1
        if: failure()
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: behat-git-notifications
          file_path: 'tests/behat/screenshots/*.png'
          file_type: 'images'
          initial_comment: 'Files found in tests/behat/screenshots, for help in diagnosing behat failures'
