name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      slack_token:
        description: "API token for slack"
      site:
        description: "Site to run tests on"
      database:
        description: "Database to pull in, normally blank"
      prnum:
        description: "Pull request number"
      gh_token:
        description: "A github token"
      LANDO_ENV:
        description: "Lando environment variables"
      SLACK_WEBHOOK:
        description: "Slack webhook to communicate with api"
      REPO:
        description: "Get current repo for gh cli command to comment on PR"
permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:

  # TODO -- use ${{secrets.site}} instead of hardcoding accessmatch.  I tried, but it didn't work.

  cypress:
    name: run cypress tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1

      - name: if this action runs, then no cypress tests found in tests/cypress/cypress/e2e/accessmatch subfolder
        run: |
          echo find tests/cypress/cypress/e2e/
          find tests/cypress/cypress/e2e/
          echo "No cypress tests found in tests/cypress/cypress/e2e/accessmatch subfolder"
        if: ${{ hashFiles('tests/cypress/cypress/e2e/accessmatch/*') == '' }}

      - id: Lando
        if: ${{ hashFiles('tests/cypress/cypress/e2e/accessmatch/*') != '' }}
        uses: necyberteam/amp_lando_start@v2
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cypress test
        if: ${{ hashFiles('tests/cypress/cypress/e2e/accessmatch/*') != '' }}
        run: |
          cd tests/cypress
          lando ssh -c 'pwd'
          lando cypress run --config baseUrl=https://${{ secrets.site }}-local.cnctci.lndo.site/ -s **/${{ secrets.site }}/**
        env:
          SITE: ${{ secrets.site }}

      - name: Tests failed - upload screenshots to slack
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' }}
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: TTX1EG9BJ
          file_path: 'tests/cypress/cypress/screenshots/**/*.png'
          initial_comment: 'Files found in tests/cypress/cypress/screenshots, for help in diagnosing test failures'

      - name: Upload screenshots Artifact
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: cypress-screenshots
          path: tests/cypress/cypress/screenshots
          retention-days: 10

      - name: if this action runs, then cypress tests failed, but no screenshots found
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') == '' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Cypress tests failed, but no screenshots found in tests/cypress/cypress/screenshots'
          SLACK_TITLE: "Cypress failure, but no screenshots found"
          SLACK_CHANNEL: cypress-git-notifications
