name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      slack_token:
        description: "API token for slack"
      site:
        description: "Site to run tests on"
      database:
        description: "Database to pull in, normally blank"
      prnum:
        description: "Pull request number"
      gh_token:
        description: "A github token"
      LANDO_ENV:
        description: "Lando environment variables"
      SLACK_WEBHOOK:
        description: "Slack webhook to communicate with api"
      REPO:
        description: "Get current repo for gh cli command to comment on PR"
permissions:
  contents: write
  actions: read
  pull-requests: write
jobs:
  cypress:
    name: Run cypress tests
    runs-on: ubuntu-latest
    steps:

      - name: create a dummy3 file to test MeilCli slack notification
        run: |
          mkdir -p dummy_folder
          echo "dummy3 file" > dummy_folder/dummy3.txt

      - name: pwd
        run: |
          pwd

      - name: Slack Notification with MeilCli/slack-upload-file@v2 to behat channel
        uses: MeilCli/slack-upload-file@v2
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: behat-git-notifications
          file_path: 'dummy_folder/*'
          file_type: 'text'
          initial_comment: 'Files found in dummy_folder/*'


      - uses: actions/checkout@v3

      - id: Lando
        uses: necyberteam/amp_lando_start@v2
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cypress test
        run: |
          pushd tests/cypress
          pwd
          lando ssh -c 'pwd'
          lando cypress run --config baseUrl=https://${{ secrets.site }}-local.cnctci.lndo.site -s **/${{ secrets.site }}/*
          popd
        env:
          SITE: ${{ secrets.site }}

      - name: ls
        if: failure()
        run: |
          pwd
          ls -l tests/cypress/cypress/screenshots
          ls -l /app/tests/cypress/cypress/screenshots
          find tests/cypress/cypress/
          find /app/tests/cypress/cypress/
          # tests\cypress\cypress\screenshots


      - name: Slack Notification Fail
        uses: MeilCli/slack-upload-file@v2
        if: failure()
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: behat-git-notifications
          file_path: 'tests/cypress/cypress/screenshots/*'
          file_type: 'images'
          initial_comment: 'Files found in tests/cypress/cypress/screenshots, for help in diagnosing test failures'
