name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      slack_token:
        description: "API token for slack"
      site:
        description: "Site to run tests on"
      directory:
        description: "Directory to run tests in"
      database:
        description: "Database to pull in, normally blank"
      prnum:
        description: "Pull request number"
      gh_token:
        description: "A github token"
      LANDO_ENV:
        description: "Lando environment variables"
      SLACK_WEBHOOK:
        description: "Slack webhook to communicate with api"
      REPO:
        description: "Get current repo for gh cli command to comment on PR"
      EVENT_NAME:
        description: "Event name"
permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:

  cypress:
    name: run cypress tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1

      - id: Lando
        if: ${{ github.event_name == 'pull_request' }}
        uses: necyberteam/amp_lando_start@v2.3
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cypress test
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo 'Clear watchdog logs'
          lando drush watchdog:delete all -y
          echo 'Cypress test'
          vendor/bin/robo cypress $DIR
        env:
          SITE: ${{ secrets.site }}
          DIR: ${{ secrets.directory }}

      - name: Get logs
        if: ${{ failure() && github.event_name == 'pull_request' }}
        run: lando drush wd-show --count=10000

      - name: Tests failed - upload screenshots to slack
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' && github.event_name == 'pull_request'}}
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: C05UU6WN1V4
          file_path: 'tests/cypress/cypress/screenshots/**/*.png'
          initial_comment: 'Files found in tests/cypress/cypress/screenshots, for help in diagnosing test failures'

      - name: Upload screenshots Artifact
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' && github.event_name == 'pull_request'}}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: cypress-screenshots-${{ secrets.site }}
          path: tests/cypress/cypress/screenshots
          retention-days: 10

      - name: if this action runs, then cypress tests failed, but no screenshots found
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') == '' && github.event_name == 'pull_request'}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Cypress tests failed, but no screenshots found in tests/cypress/cypress/screenshots'
          SLACK_TITLE: "Cypress failure, but no screenshots found"
          SLACK_CHANNEL: cypress-git-notifications

      - name: Merge Group
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          echo 'Let Merge Queue pass'
