name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      slack_token:
        description: "API token for slack"
      site:
        description: "Site to run tests on"
      database:
        description: "Database to pull in, normally blank"
      prnum:
        description: "Pull request number"
      gh_token:
        description: "A github token"
      LANDO_ENV:
        description: "Lando environment variables"
      SLACK_WEBHOOK:
        description: "Slack webhook to communicate with api"
      REPO:
        description: "Get current repo for gh cli command to comment on PR"
permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:

  checkout-and-find-tests:
    name: checkout the branch and look for cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Give error if no cypress tests found in tests/cypress/cypress/e2e/accessmatch subfolder
        run: |
          echo find tests/cypress/cypress/e2e/accessmatch
          find tests/cypress/cypress/e2e/accessmatch
          echo "No cypress tests found in tests/cypress/cypress/e2e/accessmatch subfolder"
          exit -1
        if: ${{ hashFiles('tests/cypress/cypress/e2e/accessmatch/*') == '' }}

  cypress:
    needs: checkout-and-find-tests
    name: Run cypress tests
    runs-on: ubuntu-latest
    steps:
      - id: Lando
        uses: necyberteam/amp_lando_start@v2
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cypress test
        run: |
          cd tests/cypress
          lando ssh -c 'pwd'
          lando cypress run --config baseUrl=https://${{ secrets.site }}-local.cnctci.lndo.site -s **/${{ secrets.site }}/*
        env:
          SITE: ${{ secrets.site }}

      - name: Upload screenshots to slack
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' }}
        uses: MeilCli/slack-upload-file@v2
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: cypress-git-notifications
          file_path: 'tests/cypress/cypress/screenshots/**/*.png'
          file_type: 'images'
          initial_comment: 'Files found in tests/cypress/cypress/screenshots, for help in diagnosing test failures'

      - name: No screenshots found
        if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') == '' }}
        run: |
          echo "No cypress screenshots found"

